import { InterviewQuestion } from '../store/interviewSlice';

export const questionSets: InterviewQuestion[][] = [
  // Set 1
  [
    { id: '1_e1', question: 'What is JSX in React?', options: ['A) A templating engine', 'B) A syntax extension for JavaScript', 'C) A CSS preprocessor', 'D) A state management library'], difficulty: 'easy', timeLimit: 20 },
    { id: '1_e2', question: 'What does the `useState` hook return?', options: ['A) A single value', 'B) An object with a value and a setter', 'C) An array with the current state and a function to update it', 'D) A function to fetch data'], difficulty: 'easy', timeLimit: 20 },
    { id: '1_m1', question: 'What is the difference between `useEffect` and `useLayoutEffect`?', options: ['A) `useLayoutEffect` runs synchronously after all DOM mutations', 'B) `useEffect` is for class components only', 'C) They are identical', 'D) `useLayoutEffect` runs before the component renders'], difficulty: 'medium', timeLimit: 60 },
    { id: '1_m2', question: 'What is "prop drilling" and how can it be avoided?', options: ['A) Passing props through many levels; avoided with Context API or Redux', 'B) A performance optimization technique', 'C) A way to dynamically generate props', 'D) An error when a prop is not defined'], difficulty: 'medium', timeLimit: 60 },
    { id: '1_h1', question: 'What is Server-Side Rendering (SSR) and what are its main advantages?', options: ['A) It improves performance and SEO by rendering pages on the server', 'B) It is a way to write server-side code in React', 'C) It is a client-side only rendering technique', 'D) It helps with styling components'], difficulty: 'hard', timeLimit: 120 },
    { id: '1_h2', question: 'How does the Node.js event loop work?', options: ['A) It runs on the main thread and handles all asynchronous operations', 'B) It is a multi-threaded process for handling requests', 'C) It is a browser-only feature', 'D) It is a loop that only handles user input'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 2
  [
    { id: '2_e1', question: 'What is a React Component?', options: ['A) A CSS class', 'B) A function or class that returns a React element', 'C) A JavaScript data type', 'D) A database model'], difficulty: 'easy', timeLimit: 20 },
    { id: '2_e2', question: 'How do you pass data from a parent component to a child component?', options: ['A) Using state', 'B) Using props', 'C) Using context', 'D) Using refs'], difficulty: 'easy', timeLimit: 20 },
    { id: '2_m1', question: 'What is the difference between a controlled and an uncontrolled component in React?', options: ['A) Controlled components get their value from the DOM', 'B) Uncontrolled components store their own state internally', 'C) Controlled components have their state managed by React', 'D) There is no difference'], difficulty: 'medium', timeLimit: 60 },
    { id: '2_m2', question: 'What is middleware in the context of Express.js?', options: ['A) A database client', 'B) A function that has access to the request, response, and next function', 'C) A templating engine', 'D) A frontend library'], difficulty: 'medium', timeLimit: 60 },
    { id: '2_h1', question: 'What is a closure in JavaScript and why is it useful?', options: ['A) A function that has access to its outer function\'s scope, even after the outer function has returned', 'B) A way to close a memory leak', 'C) A special type of loop', 'D) A built-in method for arrays'], difficulty: 'hard', timeLimit: 120 },
    { id: '2_h2', question: 'How can you optimize a React application for performance?', options: ['A) Using `React.memo`, `useCallback`, and `useMemo`', 'B) Code-splitting with `React.lazy`', 'C) Virtualizing long lists', 'D) All of the above'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 3
  [
    { id: '3_e1', question: 'What is the Virtual DOM?', options: ['A) A direct representation of the actual DOM', 'B) A copy of the DOM kept in memory and synced with the real DOM', 'C) A browser feature for faster rendering', 'D) A tool for virtual reality'], difficulty: 'easy', timeLimit: 20 },
    { id: '3_e2', question: 'What is the difference between `==` and `===` in JavaScript?', options: ['A) `==` compares value and type, `===` compares only value', 'B) `===` performs type coercion', 'C) `==` performs type coercion before comparison, `===` does not', 'D) They are interchangeable'], difficulty: 'easy', timeLimit: 20 },
    { id: '3_m1', question: 'What is the purpose of `React.memo`?', options: ['A) To memoize the result of a function', 'B) To prevent a component from re-rendering if its props have not changed', 'C) To handle component memory leaks', 'D) To connect to a Redux store'], difficulty: 'medium', timeLimit: 60 },
    { id: '3_m2', question: 'What is CORS and how do you handle it in a Node.js application?', options: ['A) A security mechanism that restricts cross-origin HTTP requests; handled with the `cors` middleware', 'B) A data encryption standard', 'C) A type of SQL injection', 'D) A client-side caching policy'], difficulty: 'medium', timeLimit: 60 },
    { id: '3_h1', question: 'Explain the concept of microfrontends.', options: ['A) A monolith architecture', 'B) An architectural style where a web app is composed of independent frontend applications', 'C) A specific JavaScript framework', 'D) A way to write smaller components'], difficulty: 'hard', timeLimit: 120 },
    { id: '3_h2', question: 'What is a memory leak in a Node.js application and how would you debug it?', options: ['A) When the application runs out of memory', 'B) When memory is allocated but not freed, causing usage to grow over time; debugged with tools like Heapdump', 'C) A security vulnerability', 'D) A normal part of the garbage collection process'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 4
  [
    { id: '4_e1', question: 'What is `npm`?', options: ['A) A programming language', 'B) A code editor', 'C) The default package manager for Node.js', 'D) A database system'], difficulty: 'easy', timeLimit: 20 },
    { id: '4_e2', question: 'How do you create a React app?', options: ['A) `npx create-react-app my-app`', 'B) `npm new react-app`', 'C) `react-init my-app`', 'D) By creating an `index.html` file only'], difficulty: 'easy', timeLimit: 20 },
    { id: '4_m1', question: 'What are React Hooks?', options: ['A) Functions that let you "hook into" React state and lifecycle features from function components', 'B) A way to handle HTML events', 'C) External libraries for React', 'D) CSS classes for styling'], difficulty: 'medium', timeLimit: 60 },
    { id: '4_m2', question: 'What is the difference between `Promise.all` and `Promise.race`?', options: ['A) `Promise.all` resolves when all promises resolve, `Promise.race` resolves as soon as one promise resolves or rejects', 'B) `Promise.race` is always faster', 'C) They are functionally identical', 'D) `Promise.all` is for single promises'], difficulty: 'medium', timeLimit: 60 },
    { id: '4_h1', question: 'What is JWT (JSON Web Token) and how is it used for authentication?', options: ['A) A compact, URL-safe means of representing claims between two parties, often used for stateless authentication', 'B) A session management tool', 'C) A type of cookie', 'D) A data encryption algorithm'], difficulty: 'hard', timeLimit: 120 },
    { id: '4_h2', question: 'What are WebSockets and how do they differ from HTTP?', options: ['A) They provide a full-duplex communication channel over a single TCP connection, unlike the request-response model of HTTP', 'B) They are a faster version of HTTP', 'C) They are used only for video streaming', 'D) There is no difference'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 5
  [
    { id: '5_e1', question: 'What is the root element in a standard React application?', options: ['A) `<div id="app">`', 'B) `<div id="main">`', 'C) `<div id="root">`', 'D) `<body>`'], difficulty: 'easy', timeLimit: 20 },
    { id: '5_e2', question: 'What command is used to start a local development server for a Vite-based React app?', options: ['A) `npm start`', 'B) `npm run dev`', 'C) `npm serve`', 'D) `npm build`'], difficulty: 'easy', timeLimit: 20 },
    { id: '5_m1', question: 'What is the purpose of the `useContext` hook in React?', options: ['A) To manage global state', 'B) To pass data through the component tree without having to pass props down manually at every level', 'C) To fetch data from an API', 'D) To create a new context'], difficulty: 'medium', timeLimit: 60 },
    { id: '5_m2', question: 'What is REST in the context of APIs?', options: ['A) A specific protocol', 'B) A software architectural style that defines a set of constraints for creating Web services', 'C) A database query language', 'D) A JavaScript framework'], difficulty: 'medium', timeLimit: 60 },
    { id: '5_h1', question: 'What is tree shaking in the context of modern JavaScript bundlers like Webpack or Rollup?', options: ['A) A debugging technique', 'B) The process of removing unused code (dead-code elimination) from the final bundle', 'C) A way to structure component trees', 'D) A code formatting standard'], difficulty: 'hard', timeLimit: 120 },
    { id: '5_h2', question: 'How would you prevent Cross-Site Scripting (XSS) attacks in a React application?', options: ['A) By sanitizing user input and using React\'s default data binding which escapes content', 'B) By using HTTPS exclusively', 'C) By using a strong password policy', 'D) By disabling JavaScript in the browser'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 6
  [
    { id: '6_e1', question: 'What is the role of the `render()` method in a React class component?', options: ['A) To update the state', 'B) To return the component\'s UI (JSX)', 'C) To handle user events', 'D) To fetch data'], difficulty: 'easy', timeLimit: 20 },
    { id: '6_e2', question: 'What is a "prop" in React?', options: ['A) A special keyword for loops', 'B) A way for components to receive data from their parent', 'C) A type of state', 'D) A browser event'], difficulty: 'easy', timeLimit: 20 },
    { id: '6_m1', question: 'What is the purpose of the `useReducer` hook?', options: ['A) An alternative to `useState` for managing complex state logic', 'B) To reduce the bundle size', 'C) To create a new Redux store', 'D) To handle form submissions'], difficulty: 'medium', timeLimit: 60 },
    { id: '6_m2', question: 'What is the difference between `PUT` and `POST` in HTTP?', options: ['A) `POST` is idempotent, `PUT` is not', 'B) `POST` is used to create a resource, `PUT` is used to create or update a resource idempotently', 'C) They are interchangeable', 'D) `PUT` is more secure than `POST`'], difficulty: 'medium', timeLimit: 60 },
    { id: '6_h1', question: 'What is OAuth 2.0 and how does it work at a high level?', options: ['A) An open standard for access delegation, commonly used for "Login with Google/Facebook"', 'B) A password hashing algorithm', 'C) A type of database', 'D) A JavaScript library'], difficulty: 'hard', timeLimit: 120 },
    { id: '6_h2', question: 'What is the difference between optimistic and pessimistic UI updates?', options: ['A) Optimistic UI assumes an operation will succeed and updates the UI immediately, while pessimistic waits for confirmation', 'B) Pessimistic UI is faster', 'C) Optimistic UI is a design pattern only', 'D) There is no difference'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 7
  [
    { id: '7_e1', question: 'What is the main purpose of a `package.json` file?', options: ['A) To store application code', 'B) To list project dependencies and metadata', 'C) To configure the web server', 'D) To define CSS styles'], difficulty: 'easy', timeLimit: 20 },
    { id: '7_e2', question: 'In CSS, what is the difference between `margin` and `padding`?', options: ['A) `margin` is the space inside the border, `padding` is outside', 'B) `padding` is the space inside the border, `margin` is outside', 'C) They are the same', 'D) `margin` is for horizontal space, `padding` for vertical'], difficulty: 'easy', timeLimit: 20 },
    { id: '7_m1', question: 'What is a Higher-Order Component (HOC) in React?', options: ['A) A component that renders another component', 'B) A function that takes a component and returns a new component with additional props or logic', 'C) A custom hook', 'D) The top-level App component'], difficulty: 'medium', timeLimit: 60 },
    { id: '7_m2', question: 'What is indexing in the context of databases?', options: ['A) A way to structure database tables', 'B) A technique to speed up the retrieval of records from a database file', 'C) A method for counting records', 'D) A security feature'], difficulty: 'medium', timeLimit: 60 },
    { id: '7_h1', question: 'What is code splitting?', options: ['A) Splitting code into multiple files for organization', 'B) The process of splitting a large bundle into smaller chunks that can be loaded on demand', 'C) A version control technique', 'D) A way to write comments'], difficulty: 'hard', timeLimit: 120 },
    { id: '7_h2', question: 'How can you manage environment variables in a Node.js application?', options: ['A) By hardcoding them in the source code', 'B) Using the `dotenv` package to load them from a `.env` file', 'C) Storing them in the browser\'s local storage', 'D) They cannot be managed'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 8
  [
    { id: '8_e1', question: 'What does `git clone` do?', options: ['A) Creates a new branch', 'B) Pushes changes to a remote repository', 'C) Creates a local copy of a remote repository', 'D) Deletes a repository'], difficulty: 'easy', timeLimit: 20 },
    { id: '8_e2', question: 'What is the purpose of the `alt` attribute on an `<img>` tag?', options: ['A) It provides alternative text for screen readers and when the image fails to load', 'B) It sets the image alignment', 'C) It defines the image source', 'D) It sets the image title'], difficulty: 'easy', timeLimit: 20 },
    { id: '8_m1', question: 'What is the `useCallback` hook used for?', options: ['A) To return a memoized version of a callback function that only changes if one of the dependencies has changed', 'B) To call a function on every render', 'C) To fetch data', 'D) To create a new state variable'], difficulty: 'medium', timeLimit: 60 },
    { id: '8_m2', question: 'What is the difference between SQL and NoSQL databases?', options: ['A) SQL databases are relational, while NoSQL databases are non-relational (document, key-value, etc.)', 'B) SQL is older and no longer used', 'C) NoSQL databases do not use tables', 'D) There is no significant difference'], difficulty: 'medium', timeLimit: 60 },
    { id: '8_h1', question: 'What is a "race condition" in the context of concurrent programming?', options: ['A) When two operations complete at the same time', 'B) An undesirable situation that occurs when a device or system attempts to perform two or more operations at the same time', 'C) A performance optimization technique', 'D) A type of network error'], difficulty: 'hard', timeLimit: 120 },
    { id: '8_h2', question: 'Explain how you would implement a caching strategy in a full-stack application.', options: ['A) Using client-side caching (e.g., LocalStorage)', 'B) Using server-side caching with a tool like Redis or Memcached', 'C) Using a Content Delivery Network (CDN)', 'D) All of the above'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 9
  [
    { id: '9_e1', question: 'What is HTML?', options: ['A) A styling language', 'B) A programming language', 'C) The standard markup language for creating web pages', 'D) A database'], difficulty: 'easy', timeLimit: 20 },
    { id: '9_e2', question: 'What is CSS used for?', options: ['A) To structure a web page', 'B) To describe the presentation and styling of a web page', 'C) To handle user interactions', 'D) To manage server-side logic'], difficulty: 'easy', timeLimit: 20 },
    { id: '9_m1', question: 'What is the `useMemo` hook in React?', options: ['A) It memoizes a value, recomputing it only when one of its dependencies changes', 'B) It is used for memoizing functions', 'C) It is an alternative to `useEffect`', 'D) It is for fetching data'], difficulty: 'medium', timeLimit: 60 },
    { id: '9_m2', question: 'What is a "stateless" API?', options: ['A) An API that does not store any client state on the server', 'B) An API that has no functions', 'C) An API that is not running', 'D) A deprecated API design'], difficulty: 'medium', timeLimit: 60 },
    { id: '9_h1', question: 'What is the role of a reverse proxy in a web architecture?', options: ['A) It sits in front of web servers and forwards client requests to those servers, often used for load balancing and security', 'B) It is a client-side proxy', 'C) It is a type of database', 'D) It is a tool for debugging network requests'], difficulty: 'hard', timeLimit: 120 },
    { id: '9_h2', question: 'What are the different types of testing you can perform on a full-stack application?', options: ['A) Unit testing, Integration testing', 'B) End-to-end (E2E) testing', 'C) Performance testing', 'D) All of the above'], difficulty: 'hard', timeLimit: 120 },
  ],
  // Set 10
  [
    { id: '10_e1', question: 'What is a "div" in HTML?', options: ['A) A special type of image', 'B) A generic container for flow content', 'C) A hyperlink', 'D) A form element'], difficulty: 'easy', timeLimit: 20 },
    { id: '10_e2', question: 'What does the `git commit` command do?', options: ['A) Pushes changes to the remote repository', 'B) Saves staged changes to the local repository history', 'C) Creates a new branch', 'D) Discards all local changes'], difficulty: 'easy', timeLimit: 20 },
    { id: '10_m1', question: 'What is the difference between `localStorage` and `sessionStorage`?', options: ['A) `localStorage` data persists until manually cleared, `sessionStorage` data is cleared when the page session ends', 'B) `localStorage` is more secure', 'C) `sessionStorage` can store more data', 'D) There is no difference'], difficulty: 'medium', timeLimit: 60 },
    { id: '10_m2', question: 'What is "salting" in the context of password hashing?', options: ['A) Adding a random string to a password before hashing it to prevent rainbow table attacks', 'B) A method for encrypting passwords', 'C) A way to make passwords longer', 'D) A deprecated hashing technique'], difficulty: 'medium', timeLimit: 60 },
    { id: '10_h1', question: 'What is a Docker container and how does it differ from a virtual machine?', options: ['A) Containers virtualize the OS, while VMs virtualize the hardware; containers are more lightweight', 'B) VMs are more lightweight than containers', 'C) They are the same technology', 'D) Docker is a type of virtual machine'], difficulty: 'hard', timeLimit: 120 },
    { id: '10_h2', question: 'Explain the CAP theorem in the context of distributed systems.', options: ['A) It states that a distributed system can only provide two of the following three guarantees: Consistency, Availability, and Partition tolerance', 'B) It is a theorem about CPU performance', 'C) It is a data encryption standard', 'D) It is a model for network protocols'], difficulty: 'hard', timeLimit: 120 },
  ],
];